### ISSUE TITLE
MonsterAI update broke areas it seems

### ISSUE THREAD

**Issue by sbtoonz** [T3kla/ValMods#1]
**Describe the bug**
[Error  : Unity Log] MissingFieldException: Field 'MonsterAI.m_attackPlayerObjectsWhenAlerted' not found.
Stack trace:
Areas.CritterHandler.Modify (Character critter, Areas.Containers.CTData data, System.String ctName, System.String cfg, System.Boolean keepLevel) (at <fcf1de9b5074491b97d4396451afa6c5>:0)
Areas.CritterHandler.ProcessCapturedCritter[T] (T spawner) (at <fcf1de9b5074491b97d4396451afa6c5>:0)
Areas.Patches.Patches.SpawnSystem_Spawn_Post (SpawnSystem __instance) (at <fcf1de9b5074491b97d4396451afa6c5>:0)
(wrapper dynamic-method) SpawnSystem.DMD<SpawnSystem::Spawn>(SpawnSystem,SpawnSystem/SpawnData,UnityEngine.Vector3,bool)
(wrapper dynamic-method) SpawnSystem.DMD<SpawnSystem::UpdateSpawnList>(SpawnSystem,System.Collections.Generic.List`1<SpawnSystem/SpawnData>,System.DateTime,bool)
SpawnSystem.UpdateSpawning () (at <ee628ece891b4c1c9e8a98609e9c572b>:0)

**To Reproduce**
login to game

**Expected behavior**
areas changes my animal behavior

**Comment by T3kla** [comment]
Looks like patch 0.155.7 messed the "m_attackPlayerObjectsWhenAlerted" field.
I'll patch it as soon as I can.

**Comment by T3kla** [comment]
Solved in version 1.0.1

https://valheim.thunderstore.io/package/Tekla/Areas/
https://www.nexusmods.com/valheim/mods/944
