### ISSUE TITLE
[ColorfulSigns] Update the BepInEx version

### ISSUE THREAD

**Issue by Funky18229** [T3kla/ValMods#5]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Funky18229** [comment]
on colorful signs

**Comment by T3kla** [comment]
Gonna do it right now, but why you ask? Did it break?

**Comment by Funky18229** [comment]
ty ty ty
