### ISSUE TITLE
[RemoveDeathPins] Occasionally not dying at 0 HP

### ISSUE THREAD

**Issue by Silentdarkness12** [T3kla/ValMods#7]
**Describe the bug**
Sometimes, when being killed,  the player does not die, but remains alive at 0 HP, able to move, but not able to perform any actions.

**To Reproduce**
1. Die.
2. See if you actually die.

**Expected behavior**
That the player dies when their HP hits 0.

**Screenshots**
![image](https://user-images.githubusercontent.com/5346817/134787352-ee7d4620-38e4-418e-b01a-6b587594627d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [chrome]
 - Version [19042]
**Additional context**
Worth noting that this is an intermittent issue that doesn't happen every single time.

**Comment by T3kla** [comment]
Working on it but just saw that there is a toggle now for death pins. Should this mod even exists now?

**Comment by T3kla** [comment]
Should be fixed now, pls let me know if you try it.

**Comment by Silentdarkness12** [comment]
Yeah there is, turns out this mod is redundant out. Should be alright now, though.
