### ISSUE TITLE
[DungeonReset] Cannot enter dungeon, Getting "Blocked" Message

### ISSUE THREAD

**Issue by Nex-x** [T3kla/ValMods#9]
Getting the "Blocked" message on screen when entering a dungeon.

**Comment by T3kla** [comment]
Sorry but I don't even know what mod you are talking about. I need much more info to fix this or any bug.

**Comment by Nex-x** [comment]
I'm very sorry, I thought this thread was for Dungeon Reset only not your collection of mods, my bad. It's specifically  Dungeon Reset that's not allowing us to enter dungeons after install

**Comment by T3kla** [comment]
Can't replicate the issue on my end. Can you share the list/pack of mods you are using?

**Comment by Nex-x** [comment]
Seems to be a server side issue with just one dungeon. Double checked it and that seems to be the issue. All other dungeon are resetting normally. I can still give you my mod list if you insist but I think the issue isn't related to your mod anymore, it was just coincidence that the dungeon broke after the mod was installed.

**Comment by T3kla** [comment]
Nice to know it's not my fault... yet.
Closing!
